version: '3'

services:
  go-picture-spider:
    image: go-picture-spider:0.0.1
    container_name: go-picture-spider
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai # 保证时区一致